web:
    image: realmdigital/nginx-php7.x:7.1
    container_name: realmdigital-nginx-php7.1-test-instance
    hostname: realmdigital-nginx-php7.1-test-instance
    restart: always
    net: host
    environment:
      ENABLE_XDEBUG: 1
      XDEBUG_CONFIG: "remote_host=123.123.34.34"
    ports:
      - '80:80'
      - '443:443'

